### ISSUE TITLE
missing RESTORE option

### ISSUE THREAD

**Issue by bitchecker** [dusanx/saf#3]
Hi,
this is a CR and not a real issue and is related to the “restore” option.

The main idea is to be able to restore data from a specific backup version.

**Comment by dusanx** [comment]
Development for this is already in progress and will probably end with 'time machine' type integration (sliding in time to find backup that fits), most probably initially for [https://vifm.info/](https://vifm.info/). I expect it in month or two to be ready.

Manual command to do the same will probably appear sooner, no ETA at the moment but it is in the plans.

**Comment by dusanx** [comment]
Resolved and completed in saf 0.16 with `saf revisions` and Vifm plugin integration.

[https://github.com/dusanx/saf#saf-revisions--h---quiet----verbose-012----debug-target-name-path](https://github.com/dusanx/saf#saf-revisions--h---quiet----verbose-012----debug-target-name-path)

[https://github.com/dusanx/saf#file-manager-integration](https://github.com/dusanx/saf#file-manager-integration)
